version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: local
            APP_DEBUG: "false"
            APP_KEY: base64:SomeRandomGeneratedKey=
            LOG_CHANNEL: stderr
            DB_CONNECTION: sqlite
            DB_DATABASE: /var/www/html/database/database.sqlite

    web:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "9090:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
